- name: PRELIM | pre-install python3-rpm   # needed for package_facts
  package:
    name: python3-rpm
    state: present
  tags:
  - always

- name: PRELIM - Populate installed packages facts
  package_facts:
    manager: rpm
  no_log: true
  tags:
  - always

- name: PRELIM - check /boot/grub2/grub.cfg
  stat:
    path: /boot/grub2/grub.cfg
  register: grub_cfg
  tags:
  - level1
  - scored
  - grub
  - patch
  - always

- name: PRELIM | Populate service facts
  service_facts:
  no_log: true
  tags:
  - always

- name: PRELIM | Check to see if we are booting with EFI or UEFI
  set_fact:
    booted_with_efi: "{{ ansible_facts['mounts'] | selectattr('mount', 'equalto', '/boot/efi') | list | length > 0 }}"
  changed_when: no
  check_mode: no
  args:
    warn: false