- name: SCORED | 2.1.1 | PATCH | Ensure xinetd is not installed
  package:
    name: xinetd
    state: absent
  when:
  - "'xinetd.service' in ansible_facts.services"
  - not suse15cis_xinetd_required
  - suse15cis_rule_2_1_1
  tags:
  - level1
  - patch
  - scored
  - rule_2.1.1

- name: NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service
    install {{ suse15cis_time_synchronization }}
  package:
    name: '{{ suse15cis_time_synchronization }}'
    state: present
  when:
  - suse15cis_rule_2_2_1_1
  tags:
  - level1
  - patch
  - rule_2.2.1.1

- name: 'NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service
    start '
  service:
    name: '{{ suse15cis_time_synchronization }}d'
    state: started
    enabled: yes
  when:
  - suse15cis_rule_2_2_1_1
  tags:
  - level1
  - patch
  - rule_2.2.1.1

- name: NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service
    stop ntp
  service:
    name: ntpd
    state: stopped
    enabled: no
  when:
  - suse15cis_time_synchronization == "chrony"
  - ansible_facts.services['ntpd.service'] is defined
  - ansible_facts.services['ntpd.service']["status"] != "not-found"
  - suse15cis_rule_2_2_1_1
  tags:
  - level1
  - patch
  - rule_2.2.1.1

- name: NOTSCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use | service
    stop chrony
  service:
    name: chrony
    state: stopped
    enabled: no
  ignore_errors: yes
  when:
  - suse15cis_time_synchronization != "chrony"
  - ansible_facts.services['chronyd.service'] is defined
  - ansible_facts.services['chronyd.service']["status"] != "not-found"
  - suse15cis_rule_2_2_1_1
  tags:
  - level1
  - patch
  - rule_2.2.1.1

- name: NOTSCORED | 2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured
  debug:
    msg: Not implemented - package not available on SUSE 15
  tags:
  - notimplemented

- name: SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured
  template:
    src: etc/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  when:
  - suse15cis_time_synchronization == "chrony"
  - suse15cis_rule_2_2_1_3
  tags:
  - level1
  - patch
  - rule_2.2.1.3

- name: SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd
    | 1
  lineinfile:
    dest: /etc/sysconfig/chronyd
    regexp: ^(#)?OPTIONS
    line: OPTIONS="-u chrony"
    state: present
    create: yes

- name: SCORED | 2.2.2 | PATCH | Ensure X Window System is not installed
  package:
    name: '{{ item }}'
    state: absent
  loop:
  - '@X Window System'
  - xorg-x11*
  when:
  - not suse15cis_xwindows_required
  - suse15cis_rule_2_2_2
  tags:
  - level1
  - scored
  - xwindows
  - patch
  - rule_2.2.2

- name: SCORED | 2.2.3 | PATCH | Ensure Avahi Server is not enabled
  service:
    name: avahi-daemon
    state: stopped
    enabled: no
  when:
  - not suse15cis_avahi_server
  - "'avahi-daemon.service' in services"
  - suse15cis_rule_2_2_3
  tags:
  - level1
  - scored
  - avahi
  - services
  - patch
  - rule_2.2.3

- name: SCORED | 2.2.4 | PATCH | Ensure CUPS is not enabled
  service:
    name: cups
    state: stopped
    enabled: no
  when:
  - not suse15cis_cups_server
  - "'cups.service' in services"
  - suse15cis_rule_2_2_4
  tags:
  - level1
  - scored
  - cups
  - services
  - patch
  - rule_2.2.4

- name: SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled
  service:
    name: dhcpd
    state: stopped
    enabled: no
  when:
  - not suse15cis_dhcp_server
  - "'dhcpd.service' in services"
  - suse15cis_rule_2_2_5
  tags:
  - level1
  - scored
  - dhcp
  - services
  - patch
  - rule_2.2.5

- name: SCORED | 2.2.6 | PATCH | Ensure LDAP server is not enabled
  package:
    name: slapd
    state: absent
    enabled: no
  when:
  - not suse15cis_ldap_server
  - "'slapd.service' in services"
  - suse15cis_rule_2_2_6
  tags:
  - level1
  - scored
  - ldap
  - services
  - patch
  - rule_2.2.6

- name: SCORED | 2.2.7 | PATCH | Ensure nfs-utils is not installed or the nfs-server
    service is masked | nfs server masked
  systemd:
    name: nfs-server
    state: stopped
    masked: yes
  when:
  - not suse15cis_nfs_server
  - "'nfs-server.service' in services"
  - suse15cis_rule_2_2_7
  tags:
  - level1
  - scored
  - nfs
  - services
  - patch
  - rule_2.2.7

- name: SCORED | 2.2.7 | PATCH | Ensure nfs-utils is not installed or the nfs-server
    service is masked | nfs server masked
  package:
    name: '{{ item }}'
    state: absent
  loop:
  - nfs-utils
  - nfs-kernel-server
  when:
  - not suse15cis_nfs_server
  - "'nfs-server.service' in services"
  - suse15cis_rule_2_2_7
  tags:
  - level1
  - scored
  - nfs
  - services
  - patch
  - rule_2.2.7

- name: 'SCORED | 2.2.8 | PATCH | Ensure rpcbind is not installed or the rpcbind services
    are masked '
  systemd:
    name: rpcbind
    state: stopped
    masked: yes
  when:
  - not suse15cis_nfs_rpc_server
  - "'rpcbind.socket' in services"
  - suse15cis_rule_2_2_8
  tags:
  - level1
  - scored
  - rpcbind
  - services
  - patch
  - rule_2.2.8

- name: SCORED | 2.2.8 | PATCH | Ensure rpcbind is not installed or the rpcbind services
    are masked
  package:
    name: rpcbind
    state: absent
  when:
  - not suse15cis_nfs_rpc_server
  - "'rpcbind' in packages"
  - suse15cis_rule_2_2_8
  tags:
  - level1
  - scored
  - rpcbind
  - services
  - patch
  - rule_2.2.8

- name: SCORED | 2.2.9 | PATCH | Ensure DNS Server is not enabled
  service:
    name: bind
    state: stopped
  when:
  - not suse15cis_bind
  - "'bind' in packages"
  - suse15cis_rule_2_2_9
  tags:
  - level1
  - patch
  - bind
  - rule_2.2.9

- name: SCORED | 2.2.10 | PATCH | Ensure ftp server is not installed
  package:
    name: vsftpd
    state: absent
  when:
  - not suse15cis_vsftpd_server
  - "'vsftpd' in packages"
  - suse15cis_rule_2_2_10
  tags:
  - level1
  - scored
  - vsftpd
  - services
  - patch
  - rule_2.2.10

- name: SCORED | 2.2.11 | PATCH | Ensure HTTP server is not installed
  package:
    name: '{{ item }}'
    state: absent
  loop:
  - apache
  - apache2
  - lighttpd
  - nginx
  when:
  - not suse15cis_httpd_server
  - suse15cis_rule_2_2_11
  tags:
  - level1
  - scored
  - httpd
  - services
  - patch
  - rule_2.2.11

- name: SCORED | 2.2.12 | PATCH | Ensure IMAP and POP3 server is not installed
  package:
    name: '{{ item }}'
    state: absent
  loop:
  - courier-imap
  - cyrus-imap
  - dovecot
  - dovecot23
  - nginx
  when:
  - not suse15cis_dovecot_server
  - suse15cis_rule_2_2_12
  tags:
  - level1
  - scored
  - dovecot
  - services
  - patch
  - rule_2.2.12


- name: SCORED | 2.2.13 | PATCH | Ensure Samba server is not installed
  package:
    name: samba
    state: absent
  when:
  - not suse15cis_samba
  - "'samba' in packages"
  - suse15cis_rule_2_2_13
  tags:
  - level1
  - scored
  - samba
  - services
  - patch
  - rule_2.2.13

- name: SCORED | 2.2.14 | PATCH | Ensure HTTP Proxy server is not installed
  package:
    name: squid
    state: absent
  when:
  - not suse15cis_squid_server
  - "'squid' in packages"
  - suse15cis_rule_2_2_14
  tags:
  - level1
  - scored
  - squid
  - services
  - patch
  - rule_2.2.14


- name: SCORED | 2.2.15 | PATCH | Ensure net-snmp is not installed
  package:
    name: net-snmp
    state: absent
  when:
  - not suse15cis_snmp_server
  - "'net-snmp' in packages"
  - suse15cis_rule_2_2_15
  tags:
  - level1
  - scored
  - net-snmp
  - services
  - patch
  - rule_2.2.15

- name: SCORED | 2.2.16 | PATCH | Ensure mail transfer agent is configured for local-only
    mode
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: ^(#)?inet_interfaces
    line: inet_interfaces = localhost
  when:
  - not suse15cis_is_mail_server
  - "'postfix' in packages"
  - suse15cis_rule_2_2_15
  tags:
  - level1
  - patch
  - mail
  - rule_2.2.15


- name: SCORED | 2.2.17 | PATCH | Ensure rsync is not installed or the rsyncd service
    is masked
  package:
    name: rsync
    state: absent
  when:
  - not suse15cis_rsyncd_server
  - "'rsync' in packages"
  - suse15cis_rule_2_2_17
  tags:
  - level1
  - patch
  - rsync
  - rule_2.2.17

- name: SCORED | 2.2.18 | PATCH | Ensure NFS is not installed
  package:
    name: ypserv
    state: absent
  when:
  - not suse15cis_nis_server
  - "'ypserv' in packages"
  - suse15cis_rule_2_2_18
  tags:
  - level1
  - patch
  - nis
  - rule_2.2.18


- name: SCORED | 2.2.19 | PATCH | Ensure telnet-server is not installed
  package:
    name: telnet-server
    state: absent
  when:
  - not suse15cis_telnet_server
  - "'telnet-server' in packages"
  - suse15cis_rule_2_2_19
  tags:
  - level1
  - patch
  - nis
  - rule_2.2.19


- name: SCORED | 2.3.1 | PATCH | Ensure NIS client is not installed
  package:
    name: ypbind
    state: absent
  when:
  - not suse15cis_nis_server
  - "'ypbind' in packages"
  - suse15cis_rule_2_3_1
  tags:
  - level1
  - patch
  - nis
  - rule_2.3.1

- name: SCORED | 2.3.2 | PATCH | Ensure rsh client is not installed
  package:
    name: rsh
    state: absent
  when:
  - not suse15cis_rsh_required
  - "'rsh' in packages"
  - suse15cis_rule_2_3_2
  tags:
  - level1
  - patch
  - nis
  - rule_2.3.2

- name: SCORED | 2.3.3 | PATCH | Ensure talk client is not installed
  package:
    name: talk
    state: absent
  when:
  - not suse15cis_talk_required
  - "'talk' in packages"
  - suse15cis_rule_2_3_3
  tags:
  - level1
  - patch
  - telnet
  - rule_2.3.3

- name: SCORED | 2.3.5 | PATCH | Ensure LDAP client is not installed
  package:
    name: openldap2-clients
    state: absent
  when:
  - not suse15cis_openldap_clients_required
  - "'openldap2-clients' in packages"
  - suse15cis_rule_2_3_5
  tags:
  - level1
  - patch
  - ldap
  - rule_2.3.5

- name: NOTSCORED | 2.4 | PATCH | Ensure nonessential services are removed or masked
  debug:
    msg: Not implemented - must be done manual
  tags:
  - notimplemented
  - level1
  - manual
  - rule_2.4
