- name: SCORED | 1.1.1.1 | PATCH | Ensure mounting of squashfs filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: ^(#)?install squashfs(\s|$)
    line: install squashfs /bin/true
    create: yes
  when:
  - suse15cis_rule_1_1_1_1
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.1.1
  - squashfs

- name: SCORED | 1.1.1.1 | PATCH | Remove squashfs module
  modprobe:
    name: squashfs
    state: absent
  when:
  - suse15cis_rule_1_1_1_1
  - not suse15cis_skip_for_travis
  - not suse15cis_skip_for_local_docker
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.1.1
  - squashfs

- name: SCORED | 1.1.1.2 | PATCH | Ensure mounting of udf filesystems is disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: ^(#)?install udf(\s|$)
    line: install udf /bin/true
    create: yes
  when:
  - suse15cis_rule_1_1_1_2
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.1.2
  - udf

- name: SCORED | 1.1.1.2 | PATCH | Remove udf module
  modprobe:
    name: udf
    state: absent
  when:
  - suse15cis_rule_1_1_1_2
  - not suse15cis_skip_for_travis
  - not suse15cis_skip_for_local_docker
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.1.2
  - udf

- name: SCORED | 1.1.1.3 | PATCH | Ensure mounting of msdos/fat/vfat filesystems is
    disabled
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    regexp: ^(#)?install {{ item }}(\s|$)
    line: install {{ item }} /bin/true
    create: yes
  loop:
  - msdos
  - fat
  - vfat
  when:
  - suse15cis_rule_1_1_1_3
  - not booted_with_efi
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.1.3
  - vfat


- name: SCORED | 1.1.1.3 | PATCH | Remove msdos/fat/vfat modules
  modprobe:
    name: '{{ item }}'
    state: absent
  loop:
  - msdos
  - fat
  - vfat
  when:
  - suse15cis_rule_1_1_1_3
  - not booted_with_efi
  - not suse15cis_skip_for_travis
  - not suse15cis_skip_for_local_docker
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.1.3
  - vfat

- name: SCORED | 1.1.2 | PATCH | Ensure /tmp is configured
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_2
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.2
  - notimplemented

- name: "SCORED | 1.1.3 | PATCH | Ensure noexec option set on /tmp partition\n SCORED\
    \ | 1.1.4 | PATCH | Ensure nodev option set on /tmp partition\n SCORED | 1.1.5\
    \ | PATCH | Ensure nosuid option set on /tmp partition"
  mount:
    name: /tmp
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
  when:
  - suse15cis_rule_1_1_3
  - suse15cis_rule_1_1_4
  - suse15cis_rule_1_1_5
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.3
  - rule_1.1.4
  - rule_1.1.5
  - skip_ansible_lint

- name: SCORED | 1.1.6 | PATCH | Ensure /dev/shm is configured
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_6
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.6
  - notimplemented

- name: "SCORED | 1.1.7 | PATCH | Ensure noexec option set on /dev/shm partition\n\
    \ SCORED | 1.1.8 | PATCH | Ensure nodev option set on /dev/shm partition\n SCORED\
    \ | 1.1.9 | PATCH | Ensure nosuid option set on /dev/shm partition"
  mount:
    name: /dev/shm
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
  when:
  - suse15cis_rule_1_1_7
  - suse15cis_rule_1_1_8
  - suse15cis_rule_1_1_9
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.7
  - rule_1.1.8
  - rule_1.1.9

- name: SCORED | 1.1.10 | PATCH | Ensure separate partition exists for /var
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_10
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.10
  - notimplemented


- name: SCORED | 1.1.11 | PATCH | Ensure separate partition exists for /var/tmp
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_11
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.11
  - notimplemented

- name: "SCORED | 1.1.12 | PATCH | Ensure noexec option set on /var/tmp partition\n\
    \ SCORED | 1.1.13 | PATCH | Ensure nodev option set on /var/tmp partition\n SCORED\
    \ | 1.1.14 | PATCH | Ensure nosuid option set on /var/tmp partition"
  mount:
    name: /var/tmp
    src: tmpfs
    state: mounted
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
  when:
  - suse15cis_rule_1_1_12
  - suse15cis_rule_1_1_13
  - suse15cis_rule_1_1_14
  tags:
  - level1
  - scored
  - patch
  - rule_1.1.12
  - rule_1.1.13
  - rule_1.1.14

- name: SCORED | 1.1.15 | PATCH | Ensure separate partition exists for /var/log
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_15
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.15
  - notimplemented

- name: SCORED | 1.1.16 | PATCH | Ensure separate partition exists for /var/log/audit
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_16
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.16
  - notimplemented

- name: SCORED | 1.1.17 | PATCH | Ensure separate partition exists for /home
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_1_17
  tags:
  - level2
  - scored
  - patch
  - rule_1.1.17
  - notimplemented

- name: SCORED | 1.1.18 | PATCH | Ensure nodev option set on /home partition
  mount:
    name: /home
    src: '{{ item.device }}'
    state: mounted
    fstype: '{{ item.fstype }}'
    opts: nodev
  when:
  - suse15cis_rule_1_1_18
  - item.mount == "/home"
  loop: '{{ ansible_mounts }}'
  no_log: false
  tags:
  - level1
  - patch
  - rule_1.1.18

- name: "SCORED | 1.1.19 | PATCH | Ensure noexec option set on removable media partitions\n\
    \ SCORED | 1.1.20 | PATCH | Ensure nodev option set on removable media partitions\n\
    \ SCORED | 1.1.21 | PATCH | Ensure nosuid option set on removable media partitions"
  debug:
    msg: --> Not relevant
  when:
  - suse15cis_rule_1_1_19
  - suse15cis_rule_1_1_20
  - suse15cis_rule_1_1_21
  tags:
  - level1
  - patch
  - rule_1.1.19
  - rule_1.1.20
  - rule_1.1.21

- name: SCORED | 1.1.22 | PATCH | Ensure sticky bit is set on all world-writable directories
  shell: set -o pipefail ; df --local -P | awk {'if (NR!=1) print $6'} | xargs -I
    '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t '{}'
  changed_when: no
  failed_when: no
  when:
  - suse15cis_rule_1_1_22
  tags:
  - level1
  - patch
  - rule_1.1.22

- name: SCORED | 1.1.23 | PATCH | Disable Automounting
  service:
    name: autofs
    enabled: no
  when:
  - not suse15cis_allow_autofs
  - "'autofs.service' in services"
  - suse15cis_rule_1_1_23
  tags:
  - level1
  - patch
  - rule_1.1.23

- name: SCORED | 1.2.1 | MANUAL | Ensure GPG keys are configured
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_2_1
  tags:
  - notimplemented
  - level1

- name: NOTSCORED | 1.2.2 | PATCH | Ensure package manager repositories are configured
  command: zypper repos
  register: yum_configured
  changed_when: no
  failed_when: no
  args:
    warn: false
  when:
  - suse15cis_rule_1_2_2
  tags:
  - level1
  - notscored
  - patch
  - rule_1.2.2
  - skip_ansible_lint

- name: SCORED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated - inventory
  find:
    paths:
    - /etc/zypp/repos.d
    patterns: '*.repo'
  register: package_repos
  changed_when: no
  when:
  - suse15cis_rule_1_2_3
  tags:
  - level1
  - scored
  - patch
  - rule_1.2.3

- name: SCORED | 1.2.3 | PATCH | Ensure gpgcheck is globally activated - execute
  replace:
    name: '{{ item.path }}'
    regexp: ^gpgcheck=0
    replace: gpgcheck=1
  with_items:
  - '{{ package_repos.files }}'
  - {path: /etc/zypp/zypp.conf}
  when:
  - suse15cis_rule_1_2_3
  tags:
  - level1
  - scored
  - gpgcheck
  - patch
  - rule_1.2.3

- name: SCORED | 1.3.1 | PATCH | Ensure sudo is installed
  package:
    name: sudo
    state: present
  when:
  - suse15cis_rule_1_3_1
  tags:
  - rule_1.3.1
  - level1

- name: "SCORED | 1.3.2 | PATCH | Ensure sudo commands use pty\n SCORED | 1.3.3 |\
    \ PATCH | Ensure sudo log file exists"
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_3_2
  - suse15cis_rule_1_3_3
  tags:
  - notimplemented
  - level1
  - rule_1.3.2
  - rule_1.3.3

- name: SCORED | 1.4.1 | PATCH | Ensure AIDE is installed
  package:
    name: aide
    state: present
  when:
  - suse15cis_rule_1_4_1
  tags:
  - level1
  - scored
  - aide
  - patch
  - rule_1.4.1

- name: SCORED | 1.4.1 | PATCH | Ensure AIDE is installed
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  args:
    creates: /var/lib/aide/aide.db.gz
  changed_when: no
  failed_when: no
  async: 45
  poll: 0
  when:
  - suse15cis_config_aide
  - suse15cis_rule_1_4_1
  tags:
  - level1
  - scored
  - aide
  - patch
  - rule_1.4.1

- name: SCORED | 1.4.2 | PATCH | Ensure filesystem integrity is regularly checked
  cron:
    name: Run AIDE integrity check weekly
    cron_file: "{{ suse15cis_aide_cron['cron_file'] }}"
    user: "{{ suse15cis_aide_cron['cron_user'] }}"
    minute: "{{ suse15cis_aide_cron['aide_minute'] | default('0') }}"
    hour: "{{ suse15cis_aide_cron['aide_hour'] | default('5') }}"
    day: "{{ suse15cis_aide_cron['aide_day'] | default('*') }}"
    month: "{{ suse15cis_aide_cron['aide_month'] | default('*') }}"
    weekday: "{{ suse15cis_aide_cron['aide_weekday'] | default('*') }}"
    job: "{{ suse15cis_aide_cron['aide_job'] }}"
  when:
  - suse15cis_rule_1_4_2
  tags:
  - level1
  - scored
  - aide
  - file_integrity
  - patch
  - rule_1.4.2

- name: "SCORED | 1.5.1 | PATCH | Ensure bootloader password is set\n SCORED | 1.5.3\
    \ | PATCH | Ensure authentication required for single user mode"
  debug:
    msg: Not implemented
  when:
  - suse15cis_set_boot_pass
  - suse15cis_rule_1_5_1
  - suse15cis_rule_1_5_3
  tags:
  - level1
  - notimplemented
  - scored
  - grub
  - patch
  - rule_1.5.1
  - rule_1.5.3

- name: SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted
  lineinfile:
    state: present
    dest: /etc/security/limits.conf
    regexp: ^#?\\*.*core
    line: '*                hard    core            0'
    insertafter: EOF
  when:
  - suse15cis_rule_1_6_1
  tags:
  - level1
  - scored
  - limits
  - patch
  - rule_1.6.1

- name: SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted
  sysctl:
    name: fs.suid_dumpable
    value: '0'
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
  - suse15cis_rule_1_6_1
  tags:
  - level1
  - scored
  - sysctl
  - patch
  - rule_1.6.1

- name: NOTSCORED | 1.6.2 | PATCH | Ensure XD/NX support is enabled
  shell: set -o pipefail ; dmesg|grep -E "NX|XD" | grep " active"
  changed_when: no
  failed_when: no
  when:
  - suse15cis_rule_1_6_2
  tags:
  - level1
  - level2
  - patch
  - rule_1.6.2

- name: SCORED | 1.6.3 | PATCH | Ensure address space layout randomization (ASLR)
    is enabled
  sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
  - suse15cis_rule_1_6_3
  tags:
  - level1
  - scored
  - patch
  - rule_1.6.3

- name: SCORED | 1.6.4 | PATCH | Ensure prelink is disabled
  service:
    name: prelink
    state: stopped
  when:
  - "'prelink' in packages"
  - suse15cis_rule_1_6_4
  tags:
  - level1
  - scored
  - patch
  - rule_1.6.4

- name: "NOTSCORED | 1.7.1.1 | PATCH | Ensure AppArmor is installed\n NOTSCORED |\
    \ 1.7.1.2 | PATCH | Ensure AppArmor is enabled in the bootloader configuration\n\
    \ NOTSCORED | 1.7.1.3 | PATCH | Ensure all AppArmor Profiles are in enforce or\
    \ complain mode\n NOTSCORED | 1.7.1.4 | PATCH | Ensure all AppArmor Profiles are\
    \ enforcing"
  debug:
    msg: Not implemented
  when:
  - suse15cis_rule_1_7_1_1
  - suse15cis_rule_1_7_1_2
  - suse15cis_rule_1_7_1_3
  - suse15cis_rule_1_7_1_4
  tags:
  - level1
  - scored
  - patch
  - rule_1.7.1.1
  - rule_1.7.1.2
  - rule_1.7.1.3
  - rule_1.7.1.3
  - notimplemented

- name: SCORED | 1.8.1.1 | PATCH | Ensure message of the day is configured properly
  template:
    src: etc/motd.j2
    dest: /etc/motd
  when:
  - suse15cis_rule_1_8_1_1
  tags:
  - level1
  - banner
  - patch
  - rule_1.8.1.1

- name: NOTSCORED | 1.8.1.2 | PATCH | Ensure local login warning banner is configured
    properly
  template:
    src: etc/issue.j2
    dest: /etc/issue
  when:
  - suse15cis_rule_1_8_1_2
  tags:
  - level1
  - patch
  - rule_1.8.1.2

- name: NOTSCORED | 1.8.1.3 | PATCH | Ensure remote login warning banner is configured
    properly
  template:
    src: etc/issue.net.j2
    dest: /etc/issue.net
  when:
  - suse15cis_rule_1_8_1_3
  tags:
  - level1
  - patch
  - rule_1.8.1.3

- name: NOTSCORED | 1.8.1.4 | PATCH | Ensure permissions on /etc/motd are configured
  file:
    dest: /etc/motd
    state: file
    owner: root
    group: root
    mode: 0644
  when:
  - suse15cis_rule_1_8_1_4
  tags:
  - level1
  - perms
  - patch
  - rule_1.8.1.4

- name: SCORED | 1.8.1.5 | PATCH | Ensure permissions on /etc/issue are configured
  file:
    dest: /etc/issue
    state: file
    owner: root
    group: root
    mode: 0644
  when:
  - suse15cis_rule_1_8_1_5
  tags:
  - level1
  - perms
  - patch
  - rule_1.8.1.5

- name: NOTSCORED | 1.8.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured
  file:
    dest: /etc/issue.net
    state: file
    owner: root
    group: root
    mode: 0644
  when:
  - suse15cis_rule_1_8_1_6
  tags:
  - level1
  - perms
  - patch
  - rule_1.8.1.6

- name: NOTSCORED | 1.9 | PATCH | Ensure updates, patches, and additional security
    software are installed
  package:
    name: '*'
    state: latest
  when:
  - suse15cis_rule_1_9
  tags:
  - level1
  - level2
  - patch
  - rule_1.9
  - skip_ansible_lint

- name: NOTSCORED | 1.10 | PATCH | Ensure GDM is removed or login is configured
  package:
    name: gdm
    state: absent
  when:
  - suse15cis_rule_1_10
  tags:
  - level1
  - patch
  - rule_1.10
